name: Build and publish

on: 
  push:
    tags:
    - "*" # Running this workflow only when a tag is made

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0 # Checking out the repo

    - name: Build and publish "latest" Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.PublishDockerToken }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: docker # Provide only Docker image name, tag will be automatically set to latest
