INSERT INTO Equipement(nom) VALUES ('Li Queen size');
INSERT INTO Equipement(nom) VALUES ('Lits Queen size');
INSERT INTO Equipement(nom) VALUES ('Literie Queen size');
INSERT INTO Equipement(nom) VALUES ('liT Queen size');
INSERT INTO Equipement(nom) VALUES ('LIT Queen size');
INSERT INTO Equipement(nom) VALUES ('lit Queen size');
INSERT INTO Equipement(nom) VALUES ('Li t Queen size');
INSERT INTO Equipement(nom) VALUES ('Queen Lit size');
INSERT INTO Equipement(nom) VALUES ('Queen LIT size');
INSERT INTO Equipement(nom) VALUES ('Queen lit size');
INSERT INTO Equipement(nom) VALUES ('Queen litière size');
INSERT INTO Equipement(nom) VALUES ('Queen Li t size');
INSERT INTO Equipement(nom) VALUES ('Queen Li size');
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (8, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (9, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (10, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (11, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (12, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (13, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (14, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (15, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (16, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (17, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (18, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (19, 2);
INSERT INTO Lit(idEquipement, nbPlaces) VALUES (20, 2);